#!/usr/bin/env python3
import nfa as NFA
import sys
from collections import deque
import time

def main(regex=sys.argv[1] + '⊣'):
    nfa = NFA.parse(regex)
    user_input = [line.rstrip() for line in sys.stdin.readlines()]
    for try_match in user_input:
        if nfa.match(try_match)[0]:
            print(try_match)
    
if __name__ == '__main__':
    main()

