#!/usr/bin/env python3
import nfa as NFA
import sys

def main(f1=sys.argv[1], f2=sys.argv[2]):

    #creates the individual NFAs
    n1 = NFA.NFA()
    n1.read_nfa(f1)
    n2 = NFA.NFA()
    n2.read_nfa(f2)


    union = NFA.union_nfa(n1, n2)
    union.print_nfa()


if __name__ == '__main__':
    main()

